#!/bin/bash
#
# The files ice_in, namelist, iodef.xml and xmlio_server.def
# must be saved on DATAPATH prior to running nemo
# Their "saved" names must be used in the make script used to create the submission job
#
# Larry Solheim ...June,2015

# this_host will be the current hostname as output from uname
this_host=`uname -n|awk -F. '{print $1}' -`
case $this_host in
    c1*) this_host=spica  ;;
    c2*) this_host=hadar  ;;
   ib3*) this_host=pollux ;;
 joule*) this_host=joule  ;;
      *) echo "Invalid hostname $this_host"
         exit 1
         ;;
esac

# If the user supplies a list of file names on the command line then the user supplied files
# will be saved if they exist in SOURCE_DIR. Otherwise all files in flist will be saved.
flist="namelist_ice namelist iodef.xml xmlio_server.def"
if [ -n "$1" ]; then
  flist="$@"
fi

# Prefix for each "saved" file name
pfx=cancpl_orca1_lim_

# The files to be saved must live in SOURCE_DIR
# Assume SOURCE_DIR is also where this script lives
SOURCE_DIR=$(readlink -f $(dirname $0))

# Change to SOURCE_DIR so that files may be referenced without a leading pathname
cd $SOURCE_DIR || { echo "Unable to change to directory $SOURCE_DIR"; exit 1; }

# The name of a temporary file
tmpf=xxx_$$

for fname in ${flist}; do
  if [ -s $fname ]; then
    # remove all "saved" files and then save the copy of $fname found in SOURCE_DIR
    # Copy $fname to a tmp file then save and release the tmp file
    # Note: save will replaced the tmp file by a link and release will delete the link

    rmt_cmd="cd $SOURCE_DIR;
             lsdat -d ^${pfx}$fname'.[0-9][0-9][0-9]$';
             cp $fname $tmpf;
             save $tmpf ${pfx}$fname;
             release $tmpf"

    echo "Saving $fname on hadar..."
    ssh hadar 'bash -s' -- <<< $rmt_cmd || { echo "Problem executing $rmt_cmd"; exit 1; }

    echo "Saving $fname on spica..."
    ssh spica 'bash -s' -- <<< $rmt_cmd || { echo "Problem executing $rmt_cmd"; exit 1; }

  else
    echo "$fname is not in $PWD  ...ignored"
  fi

done

