#!/bin/bash
# 
# Extracted compilation script used during the ocean-only build process
#   THIS SHOULD JUST BE USED TO GATHER ARGUMENTS FROM THE CONFIG FILE

# source config file
source experiment.cfg

# build argument list
build_nemo_opts=( "-p" "$strg_dir/executables" "-j" "12")
build_nemo_opts+=( srcpath=${strg_dir}/CanNEMO_tmp_src cfg=${config} exec=${nemo_exec} arch=${nemo_arch} )
[[ -n "${add_cpp_keys}" ]] && build_nemo_opts+=( add_key="${add_cpp_keys}" )
[[ -n "${del_cpp_keys}" ]] && build_nemo_opts+=( del_key="${del_cpp_keys}" )

# ssh to back end mach and compile
CWD=$(pwd)
ssh $(whoami)@daley << EOSSH
    cd $CWD
    echo "Compiling Nemo!"
    ${strg_dir}/CanNEMO_tmp_src/bin/build-nemo ${build_nemo_opts[@]} > .compile-cannemo-$$.log 2>&1
EOSSH
