#!/bin/bash
set -e
# 
# Extracted compilation script used during the ocean-only build process
#   THIS SHOULD JUST BE USED TO GATHER ARGUMENTS FROM THE CONFIG FILE

# set SEQ_EXP_HOME for the config file system settings section
[[ -z $SEQ_EXP_HOME ]] && SEQ_EXP_HOME=$(pwd)

# source config file
source experiment.cfg

# build argument list
build_nemo_opts=("-p $storage_dir/executables" "-j 12" "-c")
build_nemo_opts+=( xios_comp_np=8 xios_arch=$xios_arch )
build_nemo_opts+=( srcpath=${storage_dir}/CanNEMO_tmp_src cfg=${config} refcfg=${refconfig} exec=${nemo_exec} arch=${nemo_arch} )
[[ -n "${add_cpp_keys}" ]] && build_nemo_addkeys='add_key="'${add_cpp_keys}'"'
[[ -n "${del_cpp_keys}" ]] && build_nemo_delkeys='del_key="'${del_cpp_keys}'"'

# ssh to back end mach and compile
CWD=$(pwd)
ssh $(whoami)@daley << EOSSH
    cd $CWD
    echo "Compiling Nemo!"
    ${storage_dir}/CanNEMO_tmp_src/bin/build-nemo ${build_nemo_opts[@]} $build_nemo_addkeys $build_nemo_delkeys >> .compile-cannemo-$$.log 2>&1
EOSSH
