#!/bin/bash
# Setup script for nemo only mode:
#   - gets sourced by setup-nemo after it clones down the CanNEMO repo
#   - all inherited variables come from setup-nemo
#   - the bail function is inherited from setup-nemo
#======================================================================

#=====================
# Function Definitions
#=====================
# Function to prompt user to specify the necessary i/o and namelist files
get_user_namelist_io_list(){
    echo " "
    echo "*** Unrecognized CONFIG! ***"
    echo " "
    echo "This might be OK if you have just added this CONFIG to your repo, otherwise you are in trouble and should abort.
          We need to figure out which namelists (etc) you want to save from this config. The choices below relate only 
          to the *names* of files to be used. The files themselves will be extracted from the CONFIG ($CanNEMO_CONFIG) that you specified."
    echo " "
    echo "Choose an option and hit enter"
    echo "
          a) Abort \n 
          b) use physics default: 'namelist namelist_ice iodef.xml xmlio_server.def' \n
          c) use carbon (pisces/canoe) default: 'namelist namelist_ice namelist_pisces namelist_top iodef.xml xmlio_server.def' \n
          d) use carbon (cmoc) default: 'namelist namelist_ice namelist_pisces namelist_cmoc namelist_top iodef.xml xmlio_server.def'
         "
    echo " "
    read user_option
    case $user_option in
        a) bail "Aborting..." ;;
        b) namelists_and_iofiles='namelist namelist_ice namelist_top iodef.xml xmlio_server.def' ;;
        c) namelists_and_iofiles='namelist namelist_ice namelist_pisces namelist_top iodef.xml xmlio_server.def'  ;;
        d) namelists_and_iofiles='namelist namelist_ice namelist_pisces namelist_cmoc namelist_top iodef.xml xmlio_server.def' ;;
        *) bail "Aborting" ;;
    esac
}

#============
# Main Script
#============
# Set up maestro according the jobtype
if [[ "$jobtype" == 'rtd' ]] || [[ "$jobtype" == 'dumpdel' ]]; then
    # NOTE: this approach needs to be reconsidered, as it relied on specific branches of the 
    #       maestro repo, which definitely were not updated along with other codes, and WILL
    #       NOT WORK once we move maestro fully within the CanNEMO repo
    bail "RTD or Dump/Delete ONLY jobs are currently not supported..."
else
    echo "Setting up an ocean only run"

    # Get the exact checksum of the nemo version
    git_dir=${src_dir}/.git
    nemo_sha1=$(git --git-dir=${git_dir} rev-parse ${nemo_version})
    echo "Using nemo sha: $nemo_sha1"

    # CSS QUESTION: should this check be moved to 'setup-nemo'?
    [ -z "$CanNEMO_CONFIG" ] &&
        bail "The name of the configuration is required on the command line ...config=cfgname"

    #====================================================
    # Setup experiment directory (defined as SEQ_EXP_HOME)
    #====================================================
    [[ -d $nemo_runid ]] && bail "Directory $nemo_runid already exists! Aborting"
    mkdir $nemo_runid
    cd $nemo_runid
    maestro_src_dir="${src_dir}/lib/maestro"

    #--------------------
    # basic maestro setup
    #--------------------
    export SEQ_EXP_HOME=$(pwd)
    mkdir hub logs sequencing stats listings
    touch "logs/$(date '+%Y%m%d')000000_nodelog"
    makelinks -f
    export PATH=$SEQ_EXP_HOME/bin:$PATH

    # bring in additional directories/files
    ln -s ${maestro_src_dir}/modules/CanNEMO EntryModule                # entry point to sequencer modules
    ln -s ${maestro_src_dir}/modules                                    # module directory
    ln -s ${maestro_src_dir}/bin                                        # sequencing supporting binaries
    ln -s ${maestro_src_dir}/resources                                  # resource specification directory
    ln -s ${src_dir}                                                    # nemo source code
    ln -s ${maestro_src_dir}/nemo_counter_info.cfg                      # nemo counter file (CSS QUESTION: Is this still needed?)
    cp $src_dir/utils/compile_ocean_only compile_${nemo_runid}          # compilation script

    #--------------------------------------------------------------------
    # copy in experiment file and set values according to setup-nemo args
    #--------------------------------------------------------------------
    cp ${src_dir}/nemo/CONFIG/${CanNEMO_CONFIG}/EXP00/experiment.cfg .
    sed -i "s#^storage_dir=.*#storage_dir=${storage_dir}#g" experiment.cfg
    sed -i "s/RUNID=.*/RUNID=${nemo_runid}/g" experiment.cfg
    sed -i 's/.*config=.*/config='"$CanNEMO_CONFIG/" experiment.cfg
    if [ ${with_nemo_diag} = on ] ; then
       sed -i "s/with_nemo_diag=.*/with_nemo_diag=on/" experiment.cfg
    fi
    sed -i "s/SEQ_JOBNAME_PREFIX=.*/SEQ_JOBNAME_PREFIX=${nemo_runid}-/g" resources/resources.def

    # apply settings in experiment.cfg and get shell functions
    config-maestro                                          # CSS QUESTION: what does this do?
    source ${SEQ_EXP_HOME}/bin/CanNEMO_shell_functions.sh   # CSS QUESTION: this doesn't seem necessary

    #-----------------------------------
    # setup namelists and iodefinitions
    #-----------------------------------
    case $CanNEMO_CONFIG in
        # determine what namelists and iodef files we need
        CCC_ORCA025_LIM)      namelists_and_iofiles='namelist namelist_ice namelist_top iodef.xml xmlio_server.def'                               ;;
        CCC_ORCA025_LIM_CMOC) namelists_and_iofiles='namelist namelist_ice namelist_pisces namelist_cmoc namelist_top iodef.xml xmlio_server.def' ;;
        CCC_ORCA1_LIM)        namelists_and_iofiles='namelist namelist_ice namelist_top iodef.xml xmlio_server.def'                               ;;
        CCC_ORCA1_LIM_PISCES) namelists_and_iofiles='namelist namelist_ice namelist_pisces namelist_top iodef.xml xmlio_server.def'  ;;
        CCC_ORCA1_LIM_CANOE)  namelists_and_iofiles='namelist namelist_ice namelist_pisces namelist_top iodef.xml xmlio_server.def'  ;;
        CCC_ORCA1_LIM_CMOC)   namelists_and_iofiles='namelist namelist_ice namelist_pisces namelist_cmoc namelist_top iodef.xml xmlio_server.def' ;;
        CCC_ORCA1_OFF_PISCES) namelists_and_iofiles='namelist namelist_pisces namelist_top iodef.xml xmlio_server.def'  ;;
        CCC_ORCA1_OFF_CANOE)  namelists_and_iofiles='namelist namelist_pisces namelist_top iodef.xml xmlio_server.def'  ;;
        CCC_ORCA1_OFF_CMOC)   namelists_and_iofiles='namelist namelist_pisces namelist_top namelist_cmoc iodef.xml xmlio_server.def'  ;;
                         # ask user to specify if a non-standard config is used
                         *)get_user_namelist_io_list ;;
    esac
    mkdir namelists
    cd $SEQ_EXP_HOME/namelists
    for nml_io_file in $namelists_and_iofiles; do
        # link into namelist directory
        ln -s ${src_dir}/nemo/CONFIG/${CanNEMO_CONFIG}/EXP00/${nml_io_file} .
        if [[ $nml_io_file == *"namelist"* ]]; then
            # if this is a namelist file (not an iodef file), set in experiment.cfg
           sed -i "s#${nml_io_file}=.*#${nml_io_file}="'${SEQ_EXP_HOME}/namelists/'${nml_io_file}"#" ../experiment.cfg
        fi
    done
    cd $SEQ_EXP_HOME
    sed -i "s#nemo_xmlio_server_def=.*#nemo_xmlio_server_def="'${SEQ_EXP_HOME}/namelists/'xmlio_server.def"#" experiment.cfg
    sed -i "s#nemo_iodef=.*#nemo_iodef="'${SEQ_EXP_HOME}/namelists/'iodef.xml"#" experiment.cfg

    #------------------------------------
    # Aditional Config Dependent Settings
    #------------------------------------
    # Carbon Options
    CanNEMO_CONFIG_lower=$(echo ${CanNEMO_CONFIG} | tr '[:upper:]' '[:lower:]')
    if [[ $CanNEMO_CONFIG_lower == *"cmoc"* ]] || [[ $CanNEMO_CONFIG_lower == *"canoe"* ]]; then
        sed -i "s#nemo_carbon=.*#nemo_carbon=on#" experiment.cfg
        if [[ $CanNEMO_CONFIG_lower == *"cmoc"* ]]; then
            sed -i "s#nemo_cmoc=.*#nemo_cmoc=on#" experiment.cfg
        fi
        if [[ $CanNEMO_CONFIG_lower == *"off"* ]]; then
            sed -i 's#nemo_hist_file_suffix_list=.*#nemo_hist_file_suffix_list="ptrc_T diad_T"#' experiment.cfg
            sed -i 's#nemo_hist_file_freq_list=.*#nemo_hist_file_freq_list="1m     1m"#' experiment.cfg
            sed -i 's#nemo_dump_file_suff=.*#nemo_dump_file_suff="ptrc_T diad_T"#' experiment.cfg
            sed -i 's#nemo_dump_file_freq=.*#nemo_dump_file_freq="1m     1m"#' experiment.cfg
            sed -i 's#nemo_del_file_suff=.*#nemo_del_file_suff="ptrc_T diad_T"#' experiment.cfg
            sed -i 's#nemo_del_file_freq=.*#nemo_del_file_freq="1m     1m"#' experiment.cfg
        fi
    fi

    # Nemoval Resolution
    if [[ $CanNEMO_CONFIG_lower == *"orca025"* ]]; then
        sed -i "s#nemoval_res=.*#nemoval_res=025d#" experiment.cfg
    fi

    # Recommended Nemo Frequency
    echo "Setting nemo_freq, based off given config, to recommended value for 3hr wallclock time"
    case $CanNEMO_CONFIG_lower in 
        "ccc_orca1_lim")        frq="10y"   ;; 
        "ccc_orca1_lim_cmoc")   frq="5y"    ;;
        "ccc_orca1_lim_canoe")  frq="2y"    ;;
        "ccc_orca025_lim")      frq="4m"    ;;
        *) 
            echo "There is currently no recommended nemo_freq for config ${CanNEMO_CONFIG}"
            echo "Value set to 1y. Alter if desired"
            frq="1y" ;;
    esac
    if [[ ${with_nemo_diag} = on ]] && [[ ${CanNEMO_CONFIG_lower} != *"orca025"* ]]; then 
        # if nemo diag is turned on, and we aren't running a quarter degree model, set frequency to 1 year
        # CSS QUESTION: not sure why this is required.
        frq="1y"; 
    fi
    sed -i "s#nemo_freq=.*#nemo_freq=${frq}#" experiment.cfg

    #------------------------------------------------------
    # (IF BEING USED) Create inputs directory for each host
    #------------------------------------------------------
    # NOTE: Currently not used/supported
    # loop over hosts in host/input-path pairs and set them inside ${SEQ_EXP_HOME}/hub/${host}
    if [[ -n "$input_paths" ]]; then
        for hostpath in $input_paths; do
            host=${hostpath%:*}
            path=${hostpath#*:}
            ssh $host "export SEQ_EXP_HOME=$SEQ_EXP_HOME; export TRUE_HOST=$host; ${SEQ_EXP_HOME}/bin/set-inputs $path"
        done
    fi

    #-----------
    # Log Setup
    #-----------
    echo '~~~' >> .setup-nemo.log
    echo $(date) >> .setup-nemo.log
    echo 'setup-nemo ' $@ >> .setup-nemo.log
    echo 'Code corresponds to SHA1:' $nemo_sha1 >> .setup-nemo.log

    # Write log to nemo run database
    datef=$(date +"%Y-%m-%d %T")
    userf=$(whoami)

    #sqlite3 /home/ncs001/ocean_runs/ocean_runs.db  << EOF
    #                        INSERT INTO runs (runid, date, user, config, ver, repo, sha1)
    #                        values('${nemo_runid}', '${datef}', '${userf}', '${CanNEMO_CONFIG}', 
    #                               '${nemo_version}', '${nemo_repo}', '${nemo_sha1}');
#EOF

    #======================================
    # Compile/Launch simulation if desired
    #======================================
    # if the -l flag was given, launch simulation according to the desired length
    if (( launch_job == 1 )); then
        # CSS QUESTION: are we still supporting this?
        #               My feeling is that we don't need to support this.
        echo "Compiling and launching default $CanNEMO_CONFIG simulation from 0001:01 to ${rn_ln_y}:${rn_ln_m}"

        # compile
        echo "compiling..."
        ./compile_${runid} >> compile.log 2>&1    

        # considerations for quarter degree model
        if [[ $CanNEMO_CONFIG_lower == *"orca025"* ]]; then
            sed -i "s#nemo_rtd=.*#nemo_rtd=off#" experiment.cfg

            # set necessary data files for added resolution
            # grid information
            sed -i "s#orca_grid_info=.*#orca_grid_info=nemo3.4.1_orca025_mesh_mask_ngb.nc#" experiment.cfg
            # init files
            sed -i "s#nemo_data_1m_potential_temperature_nomask=.*#nemo_data_1m_potential_temperature_nomask=nemo_3.4_orca025_potemp_1m_z46_nomask_orca1jan.nc#" experiment.cfg
            sed -i "s#nemo_data_1m_salinity_nomask=.*#nemo_data_1m_salinity_nomask=nemo_3.4_orca025_salin_1m_z46_nomask_orca1jan.nc#" experiment.cfg
            sed -i "s#nemo_coordinates=.*#nemo_coordinates=nemo_3.4_orca025_coordinates_cmc.nc#" experiment.cfg
            sed -i "s#nemo_bathy_meter=.*#nemo_bathy_meter=nemo_3.4_orca025_bathy_meter_cmc.nc#" experiment.cfg
            sed -i "s#nemo_M2rowdrg=.*#nemo_M2rowdrg=nemo_3.4.1_orca025_m2rowdrg_orca1_inter.nc#" experiment.cfg
            sed -i "s#nemo_K1rowdrg=.*#nemo_K1rowdrg=nemo_3.4.1_orca025_k1rowdrg_orca1_inter.nc#" experiment.cfg
            sed -i "s#nemo_sss_data=.*#nemo_sss_data=nemo_3.4_orca025_sss_1m.nc#" experiment.cfg
            sed -i "s#nemo_chlorophyll=.*#nemo_chlorophyll=nemo_3.4.1_orca025_chlorophyll_1m_orca1.nc#" experiment.cfg
            # forcing consideration (set up to work with default forcing)
            #   - the addressing forces replacements only in default forcing section
            sed -i "/^\s*#/! s#nemo_weights_bicubic2=.*#nemo_weights_bicubic2=uncs_orca025_canesm2_weights_bicubic.nc#" experiment.cfg
            sed -i "/^\s*#/! s#nemo_weights_bilinear2=.*#nemo_weights_bilinear2=uncs_orca025_canesm2_weights_bilin.nc#" experiment.cfg
            sed -i "/^\s*#/! s#nemo_runoff_core_monthly=.*#nemo_runoff_core_monthly=nemo_3.4.1_orca025_rout_socoefr_month_r1i1p1_1979-2005-mean2.nc#" experiment.cfg
            sed -i "/^\s*sn_cnf=./ s#socoeff#socoefr#" experiment.cfg
            sed -i "/^\s*sn_cnf=./ s#weights_bil2##" experiment.cfg
            # timestep
            sed -i "s#nemo_rdt=.*#nemo_rdt=1440#" experiment.cfg
        fi

        # set run length
        sed -i "s#end=.*#end=${rn_ln_y}:${rn_ln_m}#" experiment.cfg

        # config maestro
        config-maestro 2>/dev/null || 
        bail "your desired simulation length must be set such that nemo_freq (set to ${frq}) "\
        "evenly divides into the number of months in the run. Alter 'end' or 'nemo_freq' in "\
        "experiment.cfg and try to launch again with the following command './bin/config-maestro; "\
        "expbegin -e \`pwd\` -d \`date +%Y%m%d%H%M\`"

        # launch run
        expbegin -e $(pwd) -d $(date +%Y%m%d%H%M)
    fi
fi
